# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import SimpleApp_pb2 as SimpleApp__pb2


class SimpleAppStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoginUser = channel.unary_unary(
                '/SimpleApp/LoginUser',
                request_serializer=SimpleApp__pb2.LoginUserRequest.SerializeToString,
                response_deserializer=SimpleApp__pb2.LoginUserResponse.FromString,
                )
        self.RegisterUser = channel.unary_unary(
                '/SimpleApp/RegisterUser',
                request_serializer=SimpleApp__pb2.RegisterUserRequest.SerializeToString,
                response_deserializer=SimpleApp__pb2.RegisterUserResponse.FromString,
                )
        self.getInfo = channel.unary_unary(
                '/SimpleApp/getInfo',
                request_serializer=SimpleApp__pb2.getInfoRequest.SerializeToString,
                response_deserializer=SimpleApp__pb2.getInfoResponse.FromString,
                )


class SimpleAppServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoginUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpleAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoginUser': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginUser,
                    request_deserializer=SimpleApp__pb2.LoginUserRequest.FromString,
                    response_serializer=SimpleApp__pb2.LoginUserResponse.SerializeToString,
            ),
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=SimpleApp__pb2.RegisterUserRequest.FromString,
                    response_serializer=SimpleApp__pb2.RegisterUserResponse.SerializeToString,
            ),
            'getInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.getInfo,
                    request_deserializer=SimpleApp__pb2.getInfoRequest.FromString,
                    response_serializer=SimpleApp__pb2.getInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SimpleApp.SimpleApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimpleApp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoginUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimpleApp.SimpleApp/LoginUser',
            SimpleApp__pb2.LoginUserRequest.SerializeToString,
            SimpleApp__pb2.LoginUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimpleApp.SimpleApp/RegisterUser',
            SimpleApp__pb2.RegisterUserRequest.SerializeToString,
            SimpleApp__pb2.RegisterUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimpleApp.SimpleApp/getInfo',
            SimpleApp__pb2.getInfoRequest.SerializeToString,
            SimpleApp__pb2.getInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
