# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimpleApp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fSimpleApp.proto\x12\tSimpleApp\"6\n\x10LoginUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"$\n\x11LoginUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"9\n\x13RegisterUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\'\n\x14RegisterUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0egetInfoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x0fgetInfoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe6\x01\n\tSimpleApp\x12\x46\n\tLoginUser\x12\x1b.SimpleApp.LoginUserRequest\x1a\x1c.SimpleApp.LoginUserResponse\x12O\n\x0cRegisterUser\x12\x1e.SimpleApp.RegisterUserRequest\x1a\x1f.SimpleApp.RegisterUserResponse\x12@\n\x07getInfo\x12\x19.SimpleApp.getInfoRequest\x1a\x1a.SimpleApp.getInfoResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SimpleApp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINUSERREQUEST._serialized_start=30
  _LOGINUSERREQUEST._serialized_end=84
  _LOGINUSERRESPONSE._serialized_start=86
  _LOGINUSERRESPONSE._serialized_end=122
  _REGISTERUSERREQUEST._serialized_start=124
  _REGISTERUSERREQUEST._serialized_end=181
  _REGISTERUSERRESPONSE._serialized_start=183
  _REGISTERUSERRESPONSE._serialized_end=222
  _GETINFOREQUEST._serialized_start=224
  _GETINFOREQUEST._serialized_end=252
  _GETINFORESPONSE._serialized_start=254
  _GETINFORESPONSE._serialized_end=288
  _SIMPLEAPP._serialized_start=291
  _SIMPLEAPP._serialized_end=521
# @@protoc_insertion_point(module_scope)
